language: java
jdk:
  - oraclejdk8

---
before_script:
  - "wget https://services.gradle.org/distributions/gradle-2.3-bin.zip"
  - "unzip gradle-2.3* > /dev/null"

script: "gradle-2.3*/bin/gradle test -Dspring.config.name=application-test"
