spring:
    jpa:
        open-in-view: true
        show-sql: true
        database: POSTGRESQL
        hibernate.ddl-auto: none
        repositories.enabled: true
        
    datasource:
        url: jdbc:postgresql://localhost:5432/groovy_chat
        username: gchat
        password: gchat
        
    groovy:
        template:
            prefix: classpath:/views/
            suffix: .gtl
            
# GCHAT PROPERTIES
gchat:
    ssl:
        enabled: false
    keystore:
        pass: groovychat
        type: PKCS12
        provider: SunJSSE
        alias: tomcat
        location: /security/keystore.p12