spring:
    jpa:
        open-in-view: true
        show-sql: true
        database: mysql
        hibernate.ddl-auto: none
        repositories.enabled: true
        
    datasource:
        url: jdbc:mysql://localhost:3306/groovy_chat
        username: root
        password: root
        
    groovy:
        template:
            prefix: classpath:/views/
            suffix: .gtl
            
mail:
    transport: smtp
    debug: true
    username: user
    password: secret
    smtp:
        host: smtp.gmail.com
        port: 465
        auth: true
        starttls: true
        enablessl: true
        socketfactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    
# GCHAT PROPERTIES
gchat:
    ssl:
        enabled: false
    keystore:
        pass: groovychat
        type: PKCS12
        provider: SunJSSE
        alias: tomcat
        location: /security/keystore.p12