spring:
	groovy:
		template:
			prefix: classpath:/views/
			suffix: .gtl
			
mail:
    transport: smtp
    debug: true
    username: user
    password: secret
    smtp:
        host: smtp.gmail.com
        port: 465
        auth: true
        starttls: true
        enablessl: true
        socketfactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false